spring:
  application:
    name: huyu-live-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.164.137:8848
        username: nacos
        password: nacos
        namespace: dbc7ff6a-3856-44fb-ad01-8122bd020150
dubbo:
  application:
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
server:
  port: 8081
