spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:huyu-db-sharding.yaml
    hikari:
      pool-name: huyu-user-pool
      minimum-idle: 15
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-init-sql: select 1
      connection-timeout: 4000
      max-lifetime: 60000
  application:
    name: huyu-live-user-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.164.137:8848
        username: nacos
        password: nacos
        namespace: dbc7ff6a-3856-44fb-ad01-8122bd020150
  redis:
    port: 6379
    host: 192.168.164.137
    lettuce:
      pool:
        min-idle: 10
        max-active: 50
        max-idle: 20
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.164.137:8848?username=nacos&&password=nacos&&namespace=dbc7ff6a-3856-44fb-ad01-8122bd020150
  protocol:
    name: dubbo
    port: 9091
  provider:
    timeout: 50000
huyu:
  rmq:
    producer:
      name-srv: 192.168.164.137:9876
      group-name: ${spring.application.name}
      retry-times: 3
      send-time-out: 3000
    consumer:
      group-name: ${spring.application.name}
      name-srv: 192.168.164.137:9876



#
#dubbo.application.name=huyu-live-user-provider
#dubbo.registry.address=nacos://192.168.164.134:8848?username=nacos&&password=nacos&&namespace=dbc7ff6a-3856-44fb-ad01-8122bd020150
#dubbo.server=true
#dubbo.protocol.name=dubbo
#dubbo.protocol.port=9091
#dubbo.provider.timeout=50000